- name: Stage 4 - Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # These commands run on the Ubuntu server, NOT your Windows laptop
            sudo apt-get update -y
            sudo apt-get install docker.io -y || true
            sudo systemctl start docker || true
            sudo chmod 666 /var/run/docker.sock || true
            
            # Pull and Run the app
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/multi-agent-ai:latest
            sudo docker stop ai-app || true
            sudo docker rm ai-app || true
            sudo docker run -d --name ai-app -p 80:8000 \
            -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
            ${{ secrets.DOCKER_USERNAME }}/multi-agent-ai:latest